// Apply only to learner-facing text. IDs, answers, numbers, curriculum records
// and teacher notes keep their original meaning and storage keys.
const sentences = new Map(Object.entries({
 'What would you need to know before reaching a conclusion?':'What do you need to know before you decide?',
 'Name a supported detail, an inference and a missing piece of evidence.':'Find one fact in the source. What do you think it means? What else do you need to know?',
 'Use: “The evidence suggests … because …; however …”':'Say: “I think … because the source says … But we do not know …”',
 'Use one precise source detail.':'Use one fact or number from the source.',
 'Consider another view or explanation.':'What is another way to explain this?',
 'State what the evidence cannot tell you.':'What does the evidence not tell us?',
 'Revise one part after hearing another view.':'Listen to another idea. Then make one part of your answer better.',
 'Justify your answer using the source.':'Say why you chose it. Use a detail from the source.',
 'Explain why one other option is weaker.':'Choose one other answer. Why does it not fit as well?',
 'Complete: “At first I thought …; now I think … because …”':'Finish: “First I thought … Now I think … because …”',
 'Name one question you would investigate next.':'What question would you ask next?',
 'Keep your work for your skills portfolio.':'Keep your work in your learning folder.',
 'Write one idea you remember about today’s topic.':'What do you know about this topic? Write one idea.',
 'Compare with a partner. Keep one question you want this lesson to answer.':'Tell your partner. Choose one question to ask today.',
 'Use one detail from the lesson source in your own explanation.':'Say: “I think … because the source says …”',
 'Say which part is supported and which part is still uncertain.':'What does the source show? What do you still not know?',
 'Your partner asks for evidence; improve the explanation.':'Your partner asks: “How do you know?” Add a fact to your answer.',
 'Write two precise details from the source or diagram.':'Write two facts or numbers from the source or picture.',
 'Beside each, explain what it helps you understand.':'For each one, say: “This shows …”',
 'Write one question the source does not answer.':'What does the source not tell you? Write one question.',
 'Use the task you have just tried. Write your own complete response.':'Try the task on your own. Write your answer.',
 'Show your steps, evidence or labelled diagram.':'Show your steps. You can draw and add labels.',
 'Explain why your answer fits this example.':'Say why your answer makes sense here.',
 'Exchange answers. Point to the evidence or step behind one claim.':'Swap answers. Point to a fact or step that supports an answer.',
 'Ask your partner to explain one unclear part.':'Ask your partner about one part you do not understand.',
 'Revise your own work and underline the change.':'Make your answer better. Underline what you changed.',
 'Two pairs: show different answers or methods from this task.':'Two pairs: show how you did this task.',
 'Everyone: write one similarity and one difference.':'Write one thing that is the same and one that is different.',
 'Decide which explanation is clearer and justify your choice.':'Which answer is easier to understand? Say why.',
 'Write your answer as an explanation, including evidence or working.':'Write your answer. Add a fact or show your steps.',
 'Check each claim against the source, diagram or method.':'Use the source or picture to check each answer.',
 'Correct one error or add one missing step.':'Fix one mistake or add one step.',
 '1 minute: choose two details from this lesson example.':'1 minute: choose two facts from the example.',
 '2 minutes: draw a labelled explanation or write a worked answer connecting them.':'2 minutes: draw or write how the two facts connect.',
 '2 minutes: compare with a partner. Add a missing link and explain the improvement.':'2 minutes: show your partner. Add one detail to make your answer clearer.',
 'Keep your first version and your improved version so you can show what changed.':'Keep both answers. Show what you changed.',
 '2 minutes: write a new question that can be answered using this source. Prepare an answer with evidence.':'2 minutes: write a question about the source. Write its answer with a fact to support it.',
 '2 minutes: swap questions. Answer without seeing the other pair’s explanation.':'2 minutes: swap questions with another pair. Try their question.',
 '1 minute: compare answers. Fix any ambiguity or unsupported claim.':'1 minute: check the answers together. Fix anything unclear or missing.',
 'Your question must require an explanation or a method, not just copying a word.':'Ask “Why?” or “How?” so your partner can explain.',
 'Geography studies places, physical processes, human activities and their interactions.':'Geography is the study of places, nature and people. It looks at how they affect each other.',
 'An issue is a question people can investigate; a perspective is a way of viewing it.':'An issue is a topic or problem we can study. A perspective is how someone sees it.',
 'Personal experiences can shape perspectives; a group need not share one view.':'What happens to us can change our views. People in one group can have different views.',
 'Evidence can support a claim; an opinion states a judgement or preference.':'Evidence helps us check a claim. An opinion says what someone thinks or likes.',
 'A fair inquiry question is focused, neutral and answerable.':'A good research question is clear. It does not push people towards one answer. We can find information to answer it.',
 'The accounts show different preferences, not dishonesty or universal group opinions.':'The people like different things. This does not mean someone is lying or everyone in a group agrees.',
 'Work independently; ask if an instruction is unclear.':'Work on your own. Ask if you do not understand an instruction.',
 'All case-study data in this paper is fictional.':'The people, places and numbers in these examples are made up.',
 'Use the supplied sources; no internet is needed.':'Use the sources in the paper. You do not need the internet.',
 'Illustration only: use the written source for exact facts and quantities.':'This picture helps you imagine the example. Read the source for the facts and numbers.',
 'Today’s thinking tool':'Today’s key idea',
 'Examine the evidence':'Look at the evidence',
 'Model the reasoning':'See how to explain',
 'A worked example':'An example answer',
 'Transfer the skill':'Try a new example',
 'Your exit response':'Before you finish',
 'Start and retrieve':'Remember and start',
 'Reflect on your approach':'Think about your work',
 'Make an evidence record':'Collect two facts',
 'Show your reasoning independently':'Try it on your own',
 'Compare two approaches':'Compare two answers',
 'Guided and independent practice':'Try together, then on your own',
 'Think about the issue':'Think about the topic',
 'Check understanding':'Check what you know',
 'Examine the source':'Read the source',
 'Build a better explanation':'Make your answer clearer'
}));

// Whole words/phrases only: never replace substrings inside subject terms.
const phrases = Object.entries({
 'before reaching a conclusion':'before you decide',
 'is best supported':'has the best evidence',
 'best supported':'supported best by the evidence',
 'is justified':'has evidence to support it',
 'justify your choice':'give a reason for your choice',
 'justify your answer':'give a reason for your answer',
 'state a limitation':'say what we still do not know',
 'state a limit':'say what we still do not know',
 'a competing explanation':'another possible explanation',
 'alternative explanation':'another possible explanation',
 'additional evidence':'more evidence',
 'additional comparison':'other comparison',
 'prior to':'before',
 'in order to':'to',
 'as a consequence':'as a result',
 'does not establish':'does not prove',
 'cannot establish':'cannot prove',
 'provides evidence':'gives evidence',
 'provide evidence':'give evidence',
 'numerical case-study data':'numbers in these examples',
 'numerical evidence':'evidence from numbers',
 'supplied sources':'sources given here',
 'precise details':'clear facts or numbers',
 'precise detail':'clear fact or number',
 'source detail':'detail from the source',
 'source evidence':'evidence from the source',
 'shared concern':'need they both have',
 'missing voice':'person we have not heard from',
 'working independently':'working on your own',
 'independently':'on your own',
 'collaborate':'work together',
 'participate':'take part',
 'contribute':'add an idea',
 'identify':'find',
 'indicate':'show',
 'demonstrate':'show',
 'utilise':'use',
 'utilize':'use',
 'construct':'make',
 'constructed':'made',
 'locate':'find',
 'observe':'look closely at',
 'propose':'suggest',
 'revise':'change',
 'select':'choose',
 'initial':'first',
 'subsequent':'next',
 'approximately':'about',
 'sufficient':'enough',
 'insufficient':'not enough',
 'additional':'more',
 'consequences':'results',
 'respondents':'people who answered',
 'responses':'answers',
 'rationale':'reason',
 'misconception':'mistaken idea',
 'ambiguous':'unclear',
 'ambiguity':'unclear meaning',
 'unreliable':'not reliable',
 'affordable':'low-cost',
 'purchasing':'buying',
 'purchase':'buy',
 'residents':'people who live there',
 'viewpoint':'view',
 'viewpoints':'views',
 'similarities':'things that are the same',
 'similarity':'thing that is the same'
}).sort((a,b)=>b[0].length-a[0].length).map(([from,to])=>[new RegExp('\\b'+from+'\\b','gi'),to]);

export function simpleEnglish(text) {
 if(typeof text!=='string')return text;
 let result=sentences.get(text)||text;
 for(const [pattern,replacement] of phrases)result=result.replace(pattern,match=>/^[A-Z]/.test(match)?replacement[0].toUpperCase()+replacement.slice(1):replacement);
 return result;
}
const fields=new Set(['title','lines','quote','choices','label','explanation','answerText','responseHint','footnote','cue','nextLabel','kicker','alt','caption','steps','prompt','note','outcome','sourceTitle','source']);
export function learnerText(value,key){
 if(typeof value==='string')return fields.has(key)?simpleEnglish(value):value;
 if(Array.isArray(value))return value.map(item=>learnerText(item,key));
 if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,learnerText(v,k)]));
 return value;
}
export function supportEnglish(lesson){
 lesson.stages=lesson.stages.map(stage=>({...stage,title:simpleEnglish(stage.title),frames:stage.frames.map(frame=>learnerText(frame))}));
 if(lesson.extensions)lesson.extensions=lesson.extensions.map(extra=>learnerText(extra));
 return lesson;
}
