// A second, changed case for applied board lessons. All numerical cases invented.
const rows=`
1.1.1|Your exhibit claims the planted garden is always cooler, but you measured only at noon. Which revision is justified?|It was cooler at the measured time; test other times.|Keep “always” because gardens contain plants.|A limited observation supports a limited conclusion.
1.1.2|A bridge shortens a route but its approach blocks the only riverside path. What must the evaluation include?|Both improved crossing and lost path access.|Only the shorter crossing.|One development can improve one connection while disrupting another.
1.2.1|The measured 3 cm line stays the same, but the scale changes from 40 to 80 m per cm. What happens to represented distance?|It doubles from 120 to 240 m.|It stays 120 m because the drawn line is unchanged.|Real distance depends on both drawn length and scale.
1.2.2|A ruler has a broken end but its 1 cm and 5 cm marks remain. What length lies between them?|4 cm.|5 cm.|Subtract the start reading from the end reading; the physical edge is not always zero.
1.3.1|A second count includes people walking past, while the first counted only those waiting. Can the totals be compared fairly as queue lengths?|No; use the same definition of waiting.|Yes; any two counts are comparable.|Changing what is counted can change the result independently of real queue length.
1.3.2|Your classroom observation counted 18 bags. Can this establish there are exactly 18 pupils present?|No; bags and pupils are different measures.|Yes; every bag always represents one pupil.|Some pupils may have no bag or more than one; validate the relationship before inferring attendance.
1.4.1|Two before-and-after photos were taken from different directions. What should you do before saying a building vanished?|Match the location and viewing coverage.|Treat anything outside the later frame as demolished.|Different framing can hide a feature without any real change.
1.4.2|Customers increased before the new walkway opened. How should the access explanation change?|It cannot explain the earlier increase by itself.|The later walkway must still have caused the earlier increase.|Check timing as well as spatial proximity when proposing a cause.
1.5.1|A question asks why shops cluster, but a pupil gives only “six near the gate”. What is missing?|A mechanism linking the gate to possible customers.|A second count with no reason.|The count supports the pattern but does not explain why it might occur.
1.5.2|The question changes from describe to evaluate a route. What must the answer now add?|Weigh advantages and disadvantages for the named traveller.|Only repeat its direction more loudly.|Evaluation judges suitability against criteria rather than merely describing position.
1.6.1|A survey asks only shop owners whether the new station helps trade. What would strengthen it?|Add customer evidence and examine sales over time.|Assume one interested group's view proves every effect.|Different sources test the mechanism and reduce reliance on a single perspective.
1.6.2|An older shop's sales rose after the station opened. Does this prove the station caused the rise?|No; test other changes and customer journeys.|Yes; later timing guarantees causation.|Chronology is necessary for this causal claim, but alternative explanations still need checking.
1.7.1|The faster route is muddy after rain; the traveller uses a wheeled trolley. Which factor becomes more important?|Surface condition.|Only distance, regardless of surface.|Changed conditions can change the usefulness of a route for this user.
1.7.2|Both listed paths are closed today. What is a defensible recommendation?|Seek an alternative or postpone until a usable route is confirmed.|Choose the shorter closed path anyway.|Sometimes none of the listed options meets the necessary constraints.
2.1.1|A cycle map accurately shows routes but omits bus stops. Does that alone make it inaccurate?|No; omission may reflect its purpose.|Yes; every map must include every feature.|Maps select detail; assess whether the missing information matters to the intended task.
2.1.2|A second map with the same date shows the missing path at a larger scale. Which explanation is strengthened?|The smaller-scale map omitted detail.|The path must have been built between the two dates.|The dates are the same; scale provides a better explanation for the omission.
2.2.1|A pupil uses 1 cm = 20 m for the building and 1 cm = 10 m for the yard on one plan. What needs repair?|Use one scale consistently on the plan.|Nothing; both individual calculations can be right.|Different scales distort the relative sizes on a single scaled plan.
2.2.2|A 60 m by 30 m site must fit within 15 cm by 10 cm. At 1 cm = 5 m, does it fit?|Yes: 12 cm by 6 cm.|No: 60 cm by 30 cm.|Divide both real dimensions by five before checking the page limits.
2.3.1|Two mental maps show the same landmarks but opposite turns at a junction. What is needed?|Check the starting direction and actual turn.|Assume both turns must be equally correct.|Different viewpoints may explain the discrepancy, but navigation needs a verified direction.
2.3.2|A visitor follows your route from the destination back to the start. Can all left and right instructions stay unchanged?|No; reverse the sequence and check turns for the new travel direction.|Yes; route instructions never depend on direction.|Connectivity may be the same while relative turn directions change.
2.4.1|The key says a triangle is a campsite, but one triangle labels a hospital. What should be repaired?|Make the symbol use consistent or change the key and symbols together.|Keep inconsistent meanings so the map looks varied.|A symbol needs a stable meaning within the map.
2.4.2|The main gate closes and a side gate opens. Which visitor-map edit matters first?|Reconnect the arrival route through the open gate.|Add decorative trees while keeping the closed route.|Update the route's usable connection before adding nonessential detail.
2.5.1|Point A is 231458 and B is 238451. Which movement takes A towards B?|East and south.|West and north.|Easting increases from 231 to 238 while northing decreases from 458 to 451.
2.5.2|A point is 4 tenths east and 7 north in square 2446. Which reference fits?|244467.|247464.|Attach the easting tenths to 24 and the northing tenths to 46.
2.6.1|Route A is 500 m and open. Route B is 400 m but its bridge is closed. Which is currently feasible?|A, subject to other access checks.|B because it saves 100 m.|Availability is a constraint that distance alone cannot override.
2.6.2|A printed scale bar is enlarged together with the map. Is its labelled real distance still valid?|Yes, if map and bar are resized by the same factor.|No; resizing changes the actual ground distance.|The bar and map retain the same relationship when scaled together.
2.7.1|On two maps, a route measures 2 cm at 1:25,000 and 0.2 cm at 1:250,000. Are these consistent?|Yes; both represent 500 m.|No; equal routes must have equal drawn lengths.|Different scales give different map lengths for the same ground distance.
2.7.2|A route card has legs of 250 m and 500 m. A new 100 m detour is required. What is the new total?|850 m.|750 m.|Add the detour to the original 750 m rather than keeping an outdated total.
2.8.1|Two routes have equal average gradients, but one contains a short very steep section. Can averages alone decide accessibility?|No; examine the local profile as well.|Yes; equal averages guarantee identical difficulty.|An average hides variation along a route.
2.8.2|Two maps have different contour intervals. Can closer spacing alone establish which slope is steeper?|No; account for interval and scale.|Yes; spacing is sufficient on any pair of maps.|Both horizontal and vertical changes are needed for a fair comparison.
2.9.1|A point is 0° latitude and 30°E longitude. Must it be labelled north or south?|No; it lies on the Equator.|Yes; every latitude must have N or S.|Zero latitude is the dividing line itself.
2.9.2|Two points share 20°N latitude but have different longitudes. Do they occupy the same place?|No; longitude also determines location.|Yes; latitude alone identifies one point.|A complete position needs both coordinates.
3.1.1|The 40-token ferry journey is cancelled; the only available alternative costs 55 and the budget remains 45. What now?|Neither listed option works without a change.|Take the alternative because availability removes the budget limit.|Both availability and affordability must be satisfied at the same time.
3.2.1|The physical layer shows a river crossing a country boundary. Is that automatically a mapping error?|No; physical features can cross political boundaries.|Yes; every river must stop at a border.|Political divisions do not confine natural drainage networks.
3.3.1|Moist air approaches the mountain from the opposite side. Which side is now windward?|The side facing the new incoming wind.|The original side regardless of wind direction.|Windward is defined relative to the direction the air approaches from.
3.4.1|A larger survey still asks only cycling-club volunteers. Does size alone make it representative of all residents?|No; the selection remains restricted.|Yes; any larger sample removes selection bias.|A bigger sample of a selected group can retain the same systematic limitation.
3.5.1|A new housing cluster appears away from an older roadside settlement. What description improves the map?|Linear development plus a separate nucleated cluster.|Replace every label with one category automatically.|Describe the distinct parts before simplifying the whole settlement.
3.6.1|Average clinic travel improves, but one remote district's travel time rises. What should the evaluation report?|The average improvement and the uneven effects.|Only the average because it describes every resident.|Aggregate improvement can coexist with worsening access for some groups.
3.7.1|The replacement bus can carry 30 people but 60 arrive per hour. What extra information is needed?|Bus frequency and whether capacity matches demand over time.|Only the bus colour.|Capacity per trip must be combined with trips per hour to assess service demand.
3.8.1|An alternative port adds 100 km to a shipment. What trade-off should the decision include?|Maintained delivery against added time and cost.|Only the fact that a route exists.|A working alternative can still impose important costs.
4.1.1|A mapped debris ridge and dated deposit now support past ice at a location. How should confidence change?|The claim is better supported, within the evidence's limits.|The original photograph alone has now become exact proof of everything.|New independent evidence can strengthen a claim without removing every uncertainty.
4.2.1|Ice enters the front region at 4 units while 7 melt there. Can the snout retreat despite incoming ice?|Yes; losses exceed incoming supply by 3 units.|No; any incoming ice guarantees advance.|Boundary position depends on the balance, not the existence of flow alone.
4.3.1|A rough scraper removes more material, but you also pushed it twice as hard. Can roughness alone explain the difference?|No; force changed as well.|Yes; the other change can be ignored.|Confounded variables prevent isolating the effect of roughness.
4.4.1|A photograph looks along a valley floor rather than across it. What would better test a profile claim?|A cross-section or suitable height data across the valley.|Only a longer caption on the same image.|Select evidence that measures the dimension relevant to the claim.
4.5.1|A pupil labels the hollow itself an arête. What is the key correction?|The arête is the ridge; the hollow is the corrie.|Both words always mean the same shape.|Different names distinguish remaining high ground from the eroded hollow.
4.6.1|A deposit is strongly sorted into layers by particle size. What alternative process should be considered?|Transport and deposition by flowing meltwater.|Assume all glacial-region deposits were dropped directly by ice.|Meltwater can sort sediment; location alone does not establish the depositional mechanism.
4.7.1|Path B has fragile habitat despite fewer visitors. Should all excess traffic from A automatically go to B?|No; assess B's sensitivity and capacity.|Yes; fewer visitors proves unlimited capacity.|Low current use does not guarantee that extra use is suitable.
4.8.1|A glacier loses stored ice while a wet year increases rainfall runoff. Can one high-flow year prove the ice store is growing?|No; runoff has several inputs.|Yes; river flow measures only glacier storage.|Separate precipitation, storage changes and releases when explaining flow.
5.1.1|A pollutant enters a tributary below Town A but above its junction with the main river near Town B. Which connection matters first?|The downstream path from entry towards B.|An assumed upstream path towards A.|Trace the network from the actual entry point and follow flow direction.
5.2.1|Soil is already saturated. What pathway may become more important during further rain?|Surface runoff.|Unlimited extra infiltration regardless of soil state.|Available storage and infiltration conditions influence the route taken by additional water.
5.3.1|River A is wider but River B is deeper and faster. Which has greater discharge?|The information given is insufficient without quantities.|A must have greater discharge because it is wider.|Compare cross-sectional area and velocity quantitatively, not one dimension alone.
5.4.1|Two particles have different densities as well as sizes. Can size alone predict their settling order with certainty?|No; density and flow conditions also matter.|Yes; density can never affect settling.|The simple classroom prediction depended on holding other factors comparable.
5.5.1|A cut-off channel exists but water still connects through the old bend's entrances. Is complete isolation established?|No; check whether the entrances become blocked.|Yes; every shortened river instantly forms an isolated lake.|Cut-off and full isolation are related but distinct stages.
5.6.1|Supply is 80 units; proposed allocations are 20, 30, 20 and 20. What must change?|Reduce the combined allocation by at least 10.|Nothing; each individual allocation is under 80.|The total of 90 exceeds the shared supply.
5.7.1|A deeper channel helps ships, but a survey shows loss of feeding habitat. What should happen in the evaluation?|Weigh both outcomes and examine alternatives or mitigation.|Ignore habitat because one benefit was found.|A supported benefit does not erase a supported cost.
5.8.1|Rainfall is unchanged but rapid runoff rises after paving. What is a plausible mechanism to investigate?|Reduced infiltration or altered drainage routes.|The same rainfall must guarantee the same runoff.|Land surface and drainage conditions affect how rainfall reaches the channel.
5.9.1|Warnings reach residents, but no evacuation transport is available for those who need it. What gap remains?|The ability to act on the warning.|None; information alone guarantees safe action.|A response plan needs practical capacity as well as communication.
5.10.1|A wall fits the budget but shifts faster flow towards another neighbourhood. What must the recommendation include?|The transferred risk and possible alternatives.|Only the wall's local benefit.|Evaluate effects beyond the protected site and do not assume local benefit means universal benefit.
`;
export const geographyTwists=Object.fromEntries(rows.trim().split('\n').map(line=>{
 const [id,prompt,correct,wrong,explanation]=line.split('|');return [id,{prompt,choices:[correct,wrong],answer:0,explanation}];
}));
