import {f,q,open,v,task,done,build} from './pilot-tools.js';
export function townHallLesson(common){
 const square=v('square','Design a shared square',['West and east gates must connect.','Traders need selling space.','Children need a place away from moving trolleys.','Use the grid to show a testable agreement.']);
 return build(common,'Town hall: negotiate a real layout','town-hall',[
 ['Draw before debate',4,'Every pupil first sketches a possible layout on a 6-by-4 grid. This is a fictional classroom model, not a real site design or access standard. Do not show a preferred layout.',[
 f('Who gets space in the square?','think',['Sketch 6 columns × 4 rows. Mark both gates.','Draw an initial route, market area and play area.'],{lessonVisual:square,footnote:'Fictional planning grid; cells are not real measurements.',...task('initial')})]],
 ['Make each role matter',7,'Groups of four: trader, access representative, children’s representative, chair. In groups of three share the chair duty. Each role has a priority and a concession; each pupil records a contribution. No one may speak for another role without checking.',[
 f('Read your role, prepare a request','listen',['Trader: wants 6 stall cells; can trial 4. Access: needs a clear gate-to-gate route; can accept a longer route.','Children: want 6 play cells away from trolleys; can trial 4. Chair: tests and records agreement.']),
 f('One minute for each voice','pair',['Each role states a priority and an acceptable concession.','Listeners repeat the need before proposing changes.'],{lessonVisual:square,...task('roles',240)})]],
 ['Negotiate a visible agreement',10,'The route must be connected and clear; stall and play cells may not overlap it. Accept several layouts. Each role must point to evidence in the sketch and state a remaining concern. Chair records disagreements, not forced consensus.',[
 f('Build one labelled proposal','pair',['Draw a connected gate-to-gate route. Add stalls and play cells without overlap.','Every role: point to your need in the plan and name a concession.'],{lessonVisual:square,...task('proposal',300)}),
 f('Audit the plan','pair',['Access rep traces the whole route. Trader checks selling space.','Children’s rep checks trolley conflict. Chair records one unresolved concern.'],task('audit',180))]],
 ['A constraint arrives',6,'Reveal after the first proposal. Four marked cells along the north edge are needed for temporary storage on market morning. Groups must revise the actual layout or timing, not simply promise to consider everyone.',[
 f('Market-day delivery changes the space','listen',['Four cells along the north edge are needed for storage until noon.','The gates must stay connected while deliveries happen.'],{lessonVisual:{...square,storage:true},learningRole:'evidence-reveal'}),
 f('Negotiate one revision','pair',['Each role explains how the new constraint affects them.','Revise the layout or timing. Record who accepts it and any objection.'],task('revision',180))]],
 ['Defend and check',8,'Ask an audience group to trace the route in the proposed trial conditions. Model only after groups have defended their decisions. Do not imply this schematic is safe for implementation.',[
 q('Which agreement can we test?',['Vote first; draw details later.','Label the layout, times, duties and review checks.','Give each role its first choice, even if areas overlap.','The chair agrees; other concerns go unrecorded.'],'B','A trial needs a concrete plan and a way to check it. Votes, incompatible promises or unrecorded objections do not establish a workable agreement.','agreement-check'),
 f('Compare with a possible approach','listen',['One option: keep a route clear all morning, then expand stalls after storage is removed.','Test the drawing. This may reduce morning selling space and still need revision.'],{learningRole:'model'}),
 open('A different shared space',['A library group needs discussion space while readers need quiet.','Propose a trial, one concession and a measure to review.'],'For example, trial a timed discussion period and a quiet area; check reported disruption and access with both groups. State what would make you revise it.','transfer')]],
 ['Leave with an agreement',5,'Success is a labelled plan with contributions from all roles, a concession, unresolved concern and review. Teacher notes: record whether quieter pupils can point to their own contribution; compare with independent transfer.',[
 f('Write the trial agreement','think',['My role contributed ___. We changed ___ because ___.','Our trial will be checked by ___, using ___, after one week.'],task('exit')),
 done('Show the layout, a negotiated concession, and evidence that would trigger another revision.')]]
 ]);
}
export function cityLesson(common){
 const city=v('city-plan','Design for a fictional Bishkek district',['Bus users request shelter.','Shopkeepers request loading space.','Residents request quieter evenings.','Sketch a proposal before seeing a model.']);
 const data={kind:'data',title:'Requests in a volunteer consultation',intro:false,prompt:'What do these requests tell us?',chart:{labels:['Bus users','Shopkeepers','Residents'],values:[60,20,15],unit:'requests',note:'Fictional volunteer responses may overlap. They do not represent all Bishkek residents.'},steps:['60 bus users request shelter.','20 shopkeepers request loading space.','15 residents request quieter evenings.','Counts show requests, not separate population shares.']};
 return build(common,'Future Bishkek: design, challenge, revise','city',[
 ['Your first proposal',4,'Everyone creates an initial idea before data or model. This is a fictional district and budget, not a factual description of Bishkek. Preserve the original sketch for comparison.',[
 f('What would you change here?','think',['A bus stop, shops and homes share one street.','Sketch an initial improvement. Say who it helps and who might lose out.'],{lessonVisual:city,footnote:'Fictional Bishkek district and planning costs.',...task('initial')})]],
 ['Open the evidence file',7,'The numbers are volunteer requests, possibly overlapping. Never treat them as percentages of all residents. Budget 90 tokens: shelter 60, marked loading area 30, lighting 40. Scheduling existing activity costs zero in this model but has trade-offs. Real costs are not implied.',[
 f('What did people request?','think',['Compare your first idea with these requests.','Who might be missing from this consultation?'],{lessonVisual:data,learningRole:'evidence-reveal',...task('data')}),
 f('Choose within the budget','listen',['Budget: 90 tokens. Shelter: 60. Loading area: 30. Lighting: 40.','A timing change costs 0 in this model, but may inconvenience people.']),
 f('Three jobs, one proposal','pair',['Designer sketches. Evidence checker links requests to choices.','Challenge reader checks cost and who might still lose out. Rotate roles.'],task('roles'))]],
 ['Build and defend',10,'Groups of three rotate after the first draft so every learner handles evidence and challenge. Give 5 minutes design, 3 checking, 2 defence. Do not show the worked solution yet.',[
 f('Make your proposal visible','pair',['Label changes on a street sketch and total the cost.','Include one rejected alternative and why you rejected it.'],{lessonVisual:city,...task('proposal',300)}),
 f('Test another team’s reasoning','share',['Listeners: check one cost, one source claim and one trade-off.','Authors: record the strongest challenge before responding.'],task('challenge',180))]],
 ['Meet a missing voice',6,'Reveal only after drafts. A fictional night-shift worker needs daytime sleep, so daytime deliveries are not cost-free for everyone. A parent also asks that any shelter leave the pedestrian path clear. Neither represents every member of their group.',[
 f('Two people were not consulted','listen',['A night-shift worker needs daytime quiet. A parent needs a clear pavement beside the bus stop.','Which part of your plan needs checking now?'],{lessonVisual:{...city,missing:true},learningRole:'evidence-reveal'}),
 f('Revise, then defend the change','pair',['Each person proposes one response to the new evidence.','Agree a revision or explain why you keep the plan. Name what remains uncertain.'],task('revision',180))]],
 ['Check and compare',8,'One MCQ plus a transfer prompt. A model follows the class attempts and must be evaluated, not copied. Budget and sample limitations remain explicit.',[
 q('Which claim can the consultation support?',['60 out of 95 residents prefer shelter.','Most people in Bishkek want this exact design.','These respondents raised several needs; overlap and missing voices need checking.','The largest request count settles the fairest design.'],'C','The requests are voluntary and may overlap. They identify needs in this consultation without establishing population shares or a fair final design.','data-check'),
 f('Evaluate a possible model','listen',['A 60-token shelter plus a 30-token loading area fits 90. It still needs a clear path and agreed delivery times.','It leaves lighting unfunded. Would your plan handle the trade-offs better?'],{learningRole:'model'}),
 open('Transfer: a different district',['A district asks for trees and parking, but only parking users answered the survey.','State a first step before choosing a design and one way to evaluate a trial.'],'Seek views from other users and check space, access and costs. A trial could track use and reported problems, with a review date and a reason to change the plan.','transfer')]],
 ['Make success measurable',5,'A concrete achievement includes before/after sketch, source-supported reason, cost, trade-off and review measure. Use counts of blocked paths or feedback from different users as possible checks; no individual tracking needed.',[
 f('Your proposal in four lines','think',['We changed ___. Evidence: ___. Cost: ___.','We still need to check ___. After a week we will measure ___.'],task('exit')),
 done('Show a revised design, one remaining trade-off, and a test that could change your mind.')]]
 ]);
}
