export const grade8GPPlan = {
  "id": "g8-gp-2026-2027",
  "classId": "8",
  "subjectId": "global-perspectives",
  "year": "2026–2027",
  "sessionsPerWeek": 3,
  "sessionMinutes": 40,
  "weekdays": null,
  "sourceFrequency": "2 × 40 min/week",
  "sourceFile": "Mr_Bryant_Friend_Grade_8_Global_Perspectives_Long_Term_Plan_2026-2027.xlsx",
  "sourceSheet": "G8 Global Perspectives",
  "entries": [
    {
      "id": "g8-gp-a0",
      "unit": "Assessment",
      "code": "A0",
      "title": "Stage 8 skills baseline and learning targets",
      "objective": "Demonstrate current ability to analyse perspectives and data, evaluate source credibility and argument quality, collaborate, communicate and set a precise skills-development target.",
      "month": "September",
      "quarter": "Q1",
      "objectives": "OIS-GP-A0",
      "resources": "OIS Global Perspectives skills rubric; printed source and data pack; portfolio; reflection journal",
      "bloom": "Analyse / Evaluate",
      "sourceRow": 13,
      "status": "planned"
    },
    {
      "id": "g8-gp-1.1",
      "unit": "1",
      "code": "1.1",
      "title": "From product to global supply chain",
      "objective": "Trace how an everyday product connects consumers, workers, businesses, resources and countries, using evidence to identify a globalisation issue.",
      "month": "September",
      "quarter": "Q1",
      "objectives": "78A.01; 78A.03",
      "resources": "Teacher-created printed source pack; notebook; vocabulary and perspective cards; projector if available",
      "bloom": "Understand / Analyse",
      "sourceRow": 14,
      "status": "planned"
    },
    {
      "id": "g8-gp-1.2",
      "unit": "1",
      "code": "1.2",
      "title": "Perspectives within a supply chain",
      "objective": "Compare ideas and evidence from worker, consumer, business, government and community perspectives without assuming that any group has one uniform view.",
      "month": "September",
      "quarter": "Q1",
      "objectives": "78A.01; 78Cm.02",
      "resources": "Teacher-created printed source pack; notebook; vocabulary and perspective cards; projector if available",
      "bloom": "Analyse / Evaluate",
      "sourceRow": 15,
      "status": "planned"
    },
    {
      "id": "g8-gp-1.3",
      "unit": "1",
      "code": "1.3",
      "title": "Trade, price and employment data",
      "objective": "Explain how graphical or numerical data can support contrasting arguments about global trade, prices, employment or local business.",
      "month": "September",
      "quarter": "Q1",
      "objectives": "78A.02",
      "resources": "Teacher-created printed data pack; graph templates; calculator; notebook; projector if available",
      "bloom": "Analyse",
      "sourceRow": 16,
      "status": "planned"
    },
    {
      "id": "g8-gp-1.4",
      "unit": "1",
      "code": "1.4",
      "title": "Advertising, purpose and credibility",
      "objective": "Evaluate advertisements, company claims and independent reports by considering author, purpose, evidence, date and corroboration.",
      "month": "September",
      "quarter": "Q1",
      "objectives": "78E.01",
      "resources": "Teacher-created printed source pack; notebook; vocabulary and perspective cards; projector if available",
      "bloom": "Analyse / Evaluate",
      "sourceRow": 17,
      "status": "planned"
    },
    {
      "id": "g8-gp-1.5",
      "unit": "1",
      "code": "1.5",
      "title": "Consequences of consumer choices",
      "objective": "Explain intended and unintended consequences of purchasing choices and discuss the strength of arguments for different responses.",
      "month": "October",
      "quarter": "Q1",
      "objectives": "78A.03; 78E.02; 78A.04",
      "resources": "Teacher-created printed source pack; notebook; vocabulary and perspective cards; projector if available",
      "bloom": "Analyse / Evaluate",
      "sourceRow": 18,
      "status": "planned"
    },
    {
      "id": "g8-gp-1.6",
      "unit": "1",
      "code": "1.6",
      "title": "Challenge: Ethical consumer panel",
      "objective": "Work in assigned roles to present and defend an evidence-based recommendation, respond to competing priorities and reflect on teamwork and personal perspective.",
      "month": "October",
      "quarter": "Q1",
      "objectives": "78Cl.01; 78Cl.02; 78Cm.01; 78Cm.02; 78Rf.01; 78Rf.03",
      "resources": "Role cards; discussion protocol; poster paper; markers; peer-feedback and reflection rubric",
      "bloom": "Evaluate / Create",
      "sourceRow": 19,
      "status": "planned"
    },
    {
      "id": "g8-gp-q1",
      "unit": "Assessment",
      "code": "Q1",
      "title": "Quarter 1 skills evidence review",
      "objective": "Use a portfolio, source evaluation, data explanation and panel contribution to demonstrate progress in all six Cambridge Global Perspectives skills.",
      "month": "October",
      "quarter": "Q1",
      "objectives": "OIS-GP-Q1",
      "resources": "OIS Global Perspectives skills rubric; printed source and data pack; portfolio; reflection journal",
      "bloom": "Analyse / Evaluate",
      "sourceRow": 20,
      "status": "planned"
    },
    {
      "id": "g8-gp-2.1",
      "unit": "2",
      "code": "2.1",
      "title": "Constructing balanced migration questions",
      "objective": "Construct focused, non-leading questions about why people move and how migration and urbanisation affect individuals and communities.",
      "month": "November",
      "quarter": "Q2",
      "objectives": "78Rs.01",
      "resources": "Library and teacher-curated print sources; approved online sources when available; source-recording sheet; notebook",
      "bloom": "Apply / Analyse",
      "sourceRow": 21,
      "status": "planned"
    },
    {
      "id": "g8-gp-2.2",
      "unit": "2",
      "code": "2.2",
      "title": "Push, pull and interconnected causes",
      "objective": "Explain linked causes of migration and urban growth and consequences for migrants, origin communities and destination communities.",
      "month": "November",
      "quarter": "Q2",
      "objectives": "78A.03",
      "resources": "Teacher-created printed source pack; notebook; vocabulary and perspective cards; projector if available",
      "bloom": "Analyse",
      "sourceRow": 22,
      "status": "planned"
    },
    {
      "id": "g8-gp-2.3",
      "unit": "2",
      "code": "2.3",
      "title": "Population and urbanisation data",
      "objective": "Interpret maps, graphs and numerical evidence and explain how the data supports or challenges claims about migration and city growth.",
      "month": "November",
      "quarter": "Q2",
      "objectives": "78A.02; 78Rs.04",
      "resources": "Teacher-created printed data pack; graph templates; calculator; notebook; projector if available",
      "bloom": "Analyse / Evaluate",
      "sourceRow": 23,
      "status": "planned"
    },
    {
      "id": "g8-gp-2.4",
      "unit": "2",
      "code": "2.4",
      "title": "Whose perspective is represented?",
      "objective": "Identify ideas and evidence from migrant, resident, employer, service-provider and government perspectives and evaluate whose voices may be missing.",
      "month": "November",
      "quarter": "Q2",
      "objectives": "78A.01; 78E.01",
      "resources": "Teacher-created printed source pack; notebook; vocabulary and perspective cards; projector if available",
      "bloom": "Analyse / Evaluate",
      "sourceRow": 24,
      "status": "planned"
    },
    {
      "id": "g8-gp-2.5",
      "unit": "2",
      "code": "2.5",
      "title": "Evaluating migration arguments",
      "objective": "Discuss the effectiveness of contrasting arguments by referring explicitly to claims, reasoning, structure and evidence.",
      "month": "December",
      "quarter": "Q2",
      "objectives": "78E.02; 78Cm.02",
      "resources": "Teacher-created printed source pack; notebook; vocabulary and perspective cards; projector if available",
      "bloom": "Analyse / Evaluate",
      "sourceRow": 25,
      "status": "planned"
    },
    {
      "id": "g8-gp-2.6",
      "unit": "2",
      "code": "2.6",
      "title": "Challenge: A welcoming and workable city",
      "objective": "Develop and present a balanced proposal addressing one migration or urbanisation challenge, assign roles fairly and reflect on benefits and difficulties of teamwork.",
      "month": "December",
      "quarter": "Q2",
      "objectives": "78A.04; 78Cl.01; 78Cl.02; 78Cm.01; 78Rf.02",
      "resources": "Role cards; discussion protocol; poster paper; markers; peer-feedback and reflection rubric",
      "bloom": "Evaluate / Create",
      "sourceRow": 26,
      "status": "planned"
    },
    {
      "id": "g8-gp-q2",
      "unit": "Assessment",
      "code": "Q2",
      "title": "Mid-year Global Perspectives skills assessment",
      "objective": "Analyse multiple perspectives and data, evaluate a source and argument, communicate a justified response and reflect on progress and priorities.",
      "month": "December",
      "quarter": "Q2",
      "objectives": "OIS-GP-Q2",
      "resources": "OIS Global Perspectives skills rubric; printed source and data pack; portfolio; reflection journal",
      "bloom": "Analyse / Evaluate",
      "sourceRow": 27,
      "status": "planned"
    },
    {
      "id": "g8-gp-3.1",
      "unit": "3",
      "code": "3.1",
      "title": "Climate, energy and evidence",
      "objective": "Distinguish observation, data, scientific claim, prediction and opinion in accessible sources about climate change, energy and resources.",
      "month": "January",
      "quarter": "Q3",
      "objectives": "78A.01; 78E.01",
      "resources": "Teacher-created printed source pack; notebook; vocabulary and perspective cards; projector if available",
      "bloom": "Understand / Evaluate",
      "sourceRow": 28,
      "status": "planned"
    },
    {
      "id": "g8-gp-3.2",
      "unit": "3",
      "code": "3.2",
      "title": "Interpreting climate and energy data",
      "objective": "Explain how trends, comparisons and anomalies in graphical or numerical data support different arguments while recognising uncertainty and limits.",
      "month": "January",
      "quarter": "Q3",
      "objectives": "78A.02; 78Rs.04",
      "resources": "Teacher-created printed data pack; graph templates; calculator; notebook; projector if available",
      "bloom": "Analyse / Evaluate",
      "sourceRow": 29,
      "status": "planned"
    },
    {
      "id": "g8-gp-3.3",
      "unit": "3",
      "code": "3.3",
      "title": "Comparing source credibility",
      "objective": "Evaluate government, scientific, business and media sources by considering author, purpose, evidence, date and agreement with other sources.",
      "month": "January",
      "quarter": "Q3",
      "objectives": "78E.01; 78Rs.02",
      "resources": "Library and teacher-curated print sources; approved online sources when available; source-recording sheet; notebook",
      "bloom": "Analyse / Evaluate",
      "sourceRow": 30,
      "status": "planned"
    },
    {
      "id": "g8-gp-3.4",
      "unit": "3",
      "code": "3.4",
      "title": "Causes and consequences across scales",
      "objective": "Explain linked causes and consequences of an energy or resource issue at personal, Kyrgyzstani, Central Asian and global levels.",
      "month": "January",
      "quarter": "Q3",
      "objectives": "78A.03",
      "resources": "Teacher-created printed source pack; notebook; vocabulary and perspective cards; projector if available",
      "bloom": "Analyse",
      "sourceRow": 31,
      "status": "planned"
    },
    {
      "id": "g8-gp-3.5",
      "unit": "3",
      "code": "3.5",
      "title": "Evaluating actions and trade-offs",
      "objective": "Compare proposed actions using evidence and criteria such as impact, reliability, affordability, fairness and feasibility.",
      "month": "February",
      "quarter": "Q3",
      "objectives": "78A.04; 78E.02",
      "resources": "Teacher-created printed data pack; graph templates; calculator; notebook; projector if available",
      "bloom": "Evaluate",
      "sourceRow": 32,
      "status": "planned"
    },
    {
      "id": "g8-gp-3.6",
      "unit": "3",
      "code": "3.6",
      "title": "Challenge: Kyrgyzstan energy choices briefing",
      "objective": "Collaborate to present a justified energy or resource recommendation, answer questions and reflect on how evidence affected personal perspective.",
      "month": "February",
      "quarter": "Q3",
      "objectives": "78Cl.01; 78Cl.02; 78Cm.01; 78Cm.02; 78Rf.03",
      "resources": "Role cards; discussion protocol; poster paper; markers; peer-feedback and reflection rubric",
      "bloom": "Evaluate / Create",
      "sourceRow": 33,
      "status": "planned"
    },
    {
      "id": "g8-gp-4.1",
      "unit": "4",
      "code": "4.1",
      "title": "Why societies use rules and laws",
      "objective": "Identify different perspectives on the purposes of rules and laws and explain possible consequences when rules are unclear, unfair or not followed.",
      "month": "February",
      "quarter": "Q3",
      "objectives": "78A.01; 78A.03",
      "resources": "Teacher-created printed source pack; notebook; vocabulary and perspective cards; projector if available",
      "bloom": "Understand / Analyse",
      "sourceRow": 34,
      "status": "planned"
    },
    {
      "id": "g8-gp-4.2",
      "unit": "4",
      "code": "4.2",
      "title": "Perspectives on fairness and public safety",
      "objective": "Compare evidence and reasoning from citizens, young people, schools, community organisations and authorities on a public-safety or fairness issue.",
      "month": "February",
      "quarter": "Q3",
      "objectives": "78A.01; 78Cm.02",
      "resources": "Teacher-created printed source pack; notebook; vocabulary and perspective cards; projector if available",
      "bloom": "Analyse / Evaluate",
      "sourceRow": 35,
      "status": "planned"
    },
    {
      "id": "g8-gp-4.3",
      "unit": "4",
      "code": "4.3",
      "title": "Evaluating evidence in a case study",
      "objective": "Evaluate the relevance and credibility of witness accounts, reports, statistics and media summaries in an age-appropriate community case study.",
      "month": "February",
      "quarter": "Q3",
      "objectives": "78E.01; 78Rs.02",
      "resources": "Teacher-created printed source pack; notebook; vocabulary and perspective cards; projector if available",
      "bloom": "Analyse / Evaluate",
      "sourceRow": 36,
      "status": "planned"
    },
    {
      "id": "g8-gp-4.4",
      "unit": "4",
      "code": "4.4",
      "title": "Structure and strength of arguments",
      "objective": "Discuss whether an argument is effective by tracing its claim, reasons, evidence, counterargument and conclusion.",
      "month": "March",
      "quarter": "Q3",
      "objectives": "78E.02; 78Cm.01",
      "resources": "Teacher-created printed source pack; notebook; vocabulary and perspective cards; projector if available",
      "bloom": "Analyse / Evaluate",
      "sourceRow": 37,
      "status": "planned"
    },
    {
      "id": "g8-gp-4.5",
      "unit": "4",
      "code": "4.5",
      "title": "Actions for a safer and fairer community",
      "objective": "Suggest and justify actions, compare likely consequences for different groups and listen constructively to alternative priorities.",
      "month": "March",
      "quarter": "Q3",
      "objectives": "78A.04; 78Cm.02",
      "resources": "Role cards; discussion protocol; poster paper; markers; peer-feedback and reflection rubric",
      "bloom": "Evaluate",
      "sourceRow": 38,
      "status": "planned"
    },
    {
      "id": "g8-gp-4.6",
      "unit": "4",
      "code": "4.6",
      "title": "Challenge: Community town-hall simulation",
      "objective": "Assign roles, use evidence to present a reasoned position, negotiate a shared recommendation and reflect on personal contribution and team effectiveness.",
      "month": "March",
      "quarter": "Q3",
      "objectives": "78Cl.01; 78Cl.02; 78Cm.01; 78Rf.01; 78Rf.02",
      "resources": "Role cards; discussion protocol; poster paper; markers; peer-feedback and reflection rubric",
      "bloom": "Evaluate / Create",
      "sourceRow": 39,
      "status": "planned"
    },
    {
      "id": "g8-gp-r1",
      "unit": "Review",
      "code": "R1",
      "title": "Skills clinic: Source, argument and action",
      "objective": "Use feedback to improve source evaluation, argument structure, data use, referencing, discussion contributions and written reflection before the quarterly task.",
      "month": "March",
      "quarter": "Q3",
      "objectives": "78A.01–04; 78E.01–02; 78Cm.01–02; OIS-GP-REV1",
      "resources": "OIS Global Perspectives skills rubric; printed source and data pack; portfolio; reflection journal",
      "bloom": "Analyse / Evaluate",
      "sourceRow": 40,
      "status": "planned"
    },
    {
      "id": "g8-gp-q3",
      "unit": "Assessment",
      "code": "Q3",
      "title": "Quarter 3 applied challenge",
      "objective": "Analyse an unfamiliar local-global issue, evaluate sources and arguments, justify an action, contribute to a team response and submit an individual reflection.",
      "month": "March",
      "quarter": "Q3",
      "objectives": "OIS-GP-Q3",
      "resources": "OIS Global Perspectives skills rubric; printed source and data pack; portfolio; reflection journal",
      "bloom": "Evaluate / Create",
      "sourceRow": 41,
      "status": "planned"
    },
    {
      "id": "g8-gp-5.1",
      "unit": "5",
      "code": "5.1",
      "title": "Constructing questions about AI and society",
      "objective": "Construct focused research questions about how artificial intelligence may affect learning, employment, creativity, privacy or decision-making.",
      "month": "April",
      "quarter": "Q4",
      "objectives": "78Rs.01",
      "resources": "Library and teacher-curated print sources; approved online sources when available; source-recording sheet; notebook",
      "bloom": "Apply / Analyse",
      "sourceRow": 42,
      "status": "planned"
    },
    {
      "id": "g8-gp-5.2",
      "unit": "5",
      "code": "5.2",
      "title": "Prediction, evidence and speculation",
      "objective": "Distinguish evidence-based prediction from unsupported speculation in print and multimedia claims about emerging technology.",
      "month": "April",
      "quarter": "Q4",
      "objectives": "78A.01; 78E.02",
      "resources": "Teacher-created printed source pack; notebook; vocabulary and perspective cards; projector if available",
      "bloom": "Analyse / Evaluate",
      "sourceRow": 43,
      "status": "planned"
    },
    {
      "id": "g8-gp-5.3",
      "unit": "5",
      "code": "5.3",
      "title": "Credibility, bias and corroboration",
      "objective": "Evaluate technology sources by considering expertise, purpose, commercial interest, evidence and whether other credible sources support the claim.",
      "month": "April",
      "quarter": "Q4",
      "objectives": "78E.01; 78Rs.02",
      "resources": "Library and teacher-curated print sources; approved online sources when available; source-recording sheet; notebook",
      "bloom": "Analyse / Evaluate",
      "sourceRow": 44,
      "status": "planned"
    },
    {
      "id": "g8-gp-5.4",
      "unit": "5",
      "code": "5.4",
      "title": "Access, opportunity and the digital divide",
      "objective": "Explain how numerical or graphical data supports perspectives about unequal access to technology and possible consequences for different groups.",
      "month": "April",
      "quarter": "Q4",
      "objectives": "78A.02; 78A.03",
      "resources": "Teacher-created printed data pack; graph templates; calculator; notebook; projector if available",
      "bloom": "Analyse / Evaluate",
      "sourceRow": 45,
      "status": "planned"
    },
    {
      "id": "g8-gp-5.5",
      "unit": "5",
      "code": "5.5",
      "title": "Benefits, risks and responsible choices",
      "objective": "Compare arguments about benefits and risks of AI and justify practical actions that could improve responsible use in school.",
      "month": "April",
      "quarter": "Q4",
      "objectives": "78E.02; 78A.04; 78Cm.02",
      "resources": "Teacher-created printed source pack; notebook; vocabulary and perspective cards; projector if available",
      "bloom": "Evaluate",
      "sourceRow": 46,
      "status": "planned"
    },
    {
      "id": "g8-gp-5.6",
      "unit": "5",
      "code": "5.6",
      "title": "Challenge: Responsible AI guidance for school",
      "objective": "Work in a team to create and present evidence-based guidance, reference sources, respond to questions and reflect on teamwork and perspective change.",
      "month": "April",
      "quarter": "Q4",
      "objectives": "78Cl.01; 78Cl.02; 78Cm.01; 78Rf.01; 78Rf.03",
      "resources": "Role cards; discussion protocol; poster paper; markers; peer-feedback and reflection rubric",
      "bloom": "Evaluate / Create",
      "sourceRow": 47,
      "status": "planned"
    },
    {
      "id": "g8-gp-6.1",
      "unit": "6",
      "code": "6.1",
      "title": "Issues shaping future cities",
      "objective": "Construct questions and explain connections among city growth, transport, travel, tourism, resources and quality of life.",
      "month": "April",
      "quarter": "Q4",
      "objectives": "78Rs.01; 78A.03",
      "resources": "Teacher-created printed source pack; notebook; vocabulary and perspective cards; projector if available",
      "bloom": "Analyse",
      "sourceRow": 48,
      "status": "planned"
    },
    {
      "id": "g8-gp-6.2",
      "unit": "6",
      "code": "6.2",
      "title": "Stakeholder perspectives on urban change",
      "objective": "Identify ideas and evidence from residents, visitors, businesses, planners, transport users and environmental groups.",
      "month": "May",
      "quarter": "Q4",
      "objectives": "78A.01; 78Cm.02",
      "resources": "Teacher-created printed source pack; notebook; vocabulary and perspective cards; projector if available",
      "bloom": "Analyse / Evaluate",
      "sourceRow": 49,
      "status": "planned"
    },
    {
      "id": "g8-gp-6.3",
      "unit": "6",
      "code": "6.3",
      "title": "Maps, transport and tourism data",
      "objective": "Explain how maps, tables and graphs support arguments about congestion, access, travel patterns, tourism or environmental impact.",
      "month": "May",
      "quarter": "Q4",
      "objectives": "78A.02; 78Rs.04",
      "resources": "Teacher-created printed data pack; graph templates; calculator; notebook; projector if available",
      "bloom": "Analyse / Evaluate",
      "sourceRow": 50,
      "status": "planned"
    },
    {
      "id": "g8-gp-6.4",
      "unit": "6",
      "code": "6.4",
      "title": "Mini-inquiry: Local travel evidence",
      "objective": "Select an ethical observation or short survey method, collect limited local evidence and record findings alongside teacher-curated sources.",
      "month": "May",
      "quarter": "Q4",
      "objectives": "78Rs.03; 78Rs.04; 78Cl.02",
      "resources": "Library and teacher-curated print sources; approved online sources when available; source-recording sheet; notebook",
      "bloom": "Apply / Analyse",
      "sourceRow": 51,
      "status": "planned"
    },
    {
      "id": "g8-gp-6.5",
      "unit": "6",
      "code": "6.5",
      "title": "Comparing options and justifying action",
      "objective": "Evaluate possible city or transport improvements against impact, cost, inclusion, sustainability and feasibility, then justify a preferred action.",
      "month": "May",
      "quarter": "Q4",
      "objectives": "78A.04; 78E.02",
      "resources": "Teacher-created printed data pack; graph templates; calculator; notebook; projector if available",
      "bloom": "Evaluate",
      "sourceRow": 52,
      "status": "planned"
    },
    {
      "id": "g8-gp-6.6",
      "unit": "6",
      "code": "6.6",
      "title": "Challenge: Future Bishkek design forum",
      "objective": "Collaborate to communicate an evidence-based city design or policy proposal, defend decisions and reflect on personal learning and team effectiveness.",
      "month": "May",
      "quarter": "Q4",
      "objectives": "78Cl.01; 78Cm.01; 78Cm.02; 78Rf.01–04",
      "resources": "Role cards; discussion protocol; poster paper; markers; peer-feedback and reflection rubric",
      "bloom": "Evaluate / Create",
      "sourceRow": 53,
      "status": "planned"
    },
    {
      "id": "g8-gp-r2",
      "unit": "Review",
      "code": "R2",
      "title": "Portfolio consolidation and Grade 9 bridge",
      "objective": "Select and explain evidence of progress in all six skills, improve weak work using feedback and set targets for Stage 9 independence and referencing.",
      "month": "May",
      "quarter": "Q4",
      "objectives": "78Rf.04; 78Cm.01; OIS-GP-REV2",
      "resources": "OIS Global Perspectives skills rubric; printed source and data pack; portfolio; reflection journal",
      "bloom": "Analyse / Evaluate",
      "sourceRow": 54,
      "status": "planned"
    },
    {
      "id": "g8-gp-q4",
      "unit": "Assessment",
      "code": "Q4",
      "title": "Final applied skills assessment",
      "objective": "Integrate analysis, research, source and argument evaluation, collaboration, communication and reflection in an unfamiliar source-based task and short presentation.",
      "month": "May",
      "quarter": "Q4",
      "objectives": "OIS-GP-Q4",
      "resources": "OIS Global Perspectives skills rubric; printed source and data pack; portfolio; reflection journal",
      "bloom": "Analyse / Evaluate",
      "sourceRow": 55,
      "status": "planned"
    }
  ]
};
