import {languages,ui} from './i18n.js';
const root=document.querySelector('#app'),notice=document.querySelector('#status');
const KEY='learn.student.v1';let saved={lessons:{},classId:'7a',lang:'en'},storageOK=true;
try{const data=JSON.parse(localStorage.getItem(KEY));if(data&&typeof data==='object'&&!Array.isArray(data)){saved={...saved,...data,lessons:data.lessons&&typeof data.lessons==='object'&&!Array.isArray(data.lessons)?data.lessons:{}};}}catch{storageOK=false;}
const url=new URL(location.href);let lang=Object.hasOwn(languages,url.searchParams.get('lang'))?url.searchParams.get('lang'):Object.hasOwn(languages,saved.lang)?saved.lang:'en';
let lessons=[],translations={},current=null,tab='notes',bilingual=true,cardIndex=0,cardOpen=false,filter='all',subject='all',quarter='all',query='',generation=0;
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const t=key=>ui[lang][key]||ui.en[key]||key;
const tr=text=>lang==='en'?text:translations[text]||text;
const html=text=>escape(tr(text));
const prose=(text,tag='p')=>`<${tag}>${html(text)}</${tag}>${bilingual&&lang!=='en'?`<p class="english" lang="en">${escape(text)}</p>`:''}`;
const btn=(label,action,cls='',attrs='')=>`<button class="${cls}" data-action="${action}" ${attrs}>${label}</button>`;
function persist(){try{localStorage.setItem(KEY,JSON.stringify(saved));storageOK=true;return true;}catch{storageOK=false;notice.textContent=t('storageError');return false;}}
function record(id=current?.id){if(!saved.lessons[id]||typeof saved.lessons[id]!=='object')saved.lessons[id]={};return saved.lessons[id];}
function notify(text){notice.textContent=text;setTimeout(()=>{if(storageOK)notice.textContent='';},4000);}
const message=()=>`Hi Mr. Friend! I need help with ${current?current.title:'my studies'} (${saved.classId.toUpperCase()}).`;
const help=()=>`https://wa.me/996550346970?text=${encodeURIComponent(message())}`;
function art(type='geo'){
return `<svg viewBox="0 0 360 230" aria-hidden="true" class="study-art"><circle cx="290" cy="48" r="29" fill="#f6b765"/><path d="M15 169Q102 73 175 167T350 146V220H15Z" fill="#dcebc8"/><path d="M58 183l24-120 91 27 91-29 35 121-115 34Z" fill="#fffdf5" stroke="#235647" stroke-width="4"/><path d="M173 91l11 122M89 102l60 19M85 121l54 17M212 106l43-11M213 123l44-10" fill="none" stroke="#b9ccae" stroke-width="6" stroke-linecap="round"/>${type==='geo'?'<path d="M103 165l29-25 20 18 26-33 26 49 38-31 29 39" fill="none" stroke="#668c67" stroke-width="5"/><circle cx="240" cy="47" r="12" fill="#ea805f"/>':'<path d="M90 62h68v47h-38l-17 15v-15H90Z" fill="#e48763"/><path d="M205 131h65v42h-15v14l-19-14h-31Z" fill="#497b6e"/><path d="M103 78h40m-40 14h26m86 53h42m-42 14h27" stroke="white" stroke-width="4"/>'}<path d="M34 73l10 10m-10 0l10-10M302 127l11 11m-11 0l11-11" stroke="#d99955" stroke-width="3"/></svg>`;
}
function header(){return `<header class="topbar"><a class="brand" href="./" data-home><span class="brand-mark">L<span>↗</span></span><span>Learn <small>${t('library')}</small></span></a><div class="top-actions"><label class="language"><span>${t('language')}</span><select id="language">${Object.entries(languages).map(([code,label])=>`<option value="${code}" ${lang===code?'selected':''}>${label}</option>`).join('')}</select></label><a class="help-link" href="${help()}" target="_blank" rel="noopener">${t('help')} ↗</a></div></header>`;}
function unitLabel(value){return escape(value.replace(/Classroom foundations/g,t('routines')).replace(/Assessment/g,t('assessment')).replace(/Review/g,t('reviewUnit')).replace(/Week/g,t('week')).replace(/Lesson/g,t('lesson')).replace(/Unit/g,t('unit')));}
function available(){return lessons.filter(x=>x.classes.includes(saved.classId));}
function matching(){return available().filter(x=>(subject==='all'||x.subject===subject)&&(quarter==='all'||x.quarter===quarter)&&(filter==='all'||(filter==='saved'?record(x.id).bookmarked:record(x.id).confidence==='again'))&&`${x.title} ${tr(x.title)} ${x.unit}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));}
function libraryCards(){const found=matching();return `<div class="results-heading"><h2>${t(filter==='saved'?'saved':filter==='review'?'review':'allLessons')} <span>${found.length} ${t('lessons')}</span></h2></div><div class="lesson-grid">${found.map(x=>{const r=record(x.id);return `<article class="lesson-card ${x.subject==='geography'?'geo':'gp'}"><div class="card-image">${art(x.subject==='geography'?'geo':'gp')}<span class="quarter">${x.quarter==='Start'?t('start'):escape(x.quarter)}</span>${r.bookmarked?'<span class="saved-dot">♥</span>':''}</div><div class="card-body"><div class="eyebrow">${t(x.subject)} · ${unitLabel(x.unit)}</div><h3>${html(x.title)}</h3><p class="card-meta">${x.assessment?t('revision'):t('minutes')}${r.reviewed?' · ✓ '+t('complete'):''}</p><a class="card-open" href="?lesson=${encodeURIComponent(x.id)}&lang=${lang}" data-lesson="${escape(x.id)}">${t('open')} <span>↗</span></a></div></article>`;}).join('')||`<div class="empty">${t('empty')} ${btn(t('clear'),'clear','secondary')}</div>`}</div>`;}
function home(){current=null;document.title='Learn · '+t('library');const count=available().filter(x=>record(x.id).reviewed).length;const last=available().find(x=>x.id===saved.lastLesson);
root.innerHTML=header()+`<main class="library"><section class="hero"><div><p class="eyebrow">${t('eyebrow')}</p><h1>${t('hero').split('\n').join('<br>')}</h1><p class="hero-intro">${t('intro')}</p><div class="hero-pills"><span>01 ${t('read')}</span><span>02 ${t('recall')}</span><span>03 ${t('test')}</span><span>04 ${t('return')}</span></div>${last?`<a class="continue-link" href="?lesson=${encodeURIComponent(last.id)}&lang=${lang}" data-lesson="${escape(last.id)}">${t('continued')}: ${html(last.title)} →</a>`:''}</div><div class="hero-visual">${art()}<div class="progress-badge"><b>${count}</b><span>${t('complete')}<small>${t('progress')}</small></span></div></div></section><section class="filters" aria-label="${t('library')}"><label>${t('class')}<select id="class">${['7a','7b','8'].map(x=>`<option value="${x}" ${saved.classId===x?'selected':''}>${x.toUpperCase()}</option>`).join('')}</select></label><label>${t('subject')}<select id="subject">${['all','geography','global-perspectives','routines'].filter(x=>x==='all'||available().some(l=>l.subject===x)).map(x=>`<option value="${x}" ${subject===x?'selected':''}>${t(x)}</option>`).join('')}</select></label><label>${t('quarter')}<select id="quarter">${['all','Start','Q1','Q2','Q3','Q4'].map(x=>`<option value="${x}" ${quarter===x?'selected':''}>${x==='all'?t('any'):x==='Start'?t('start'):x}</option>`).join('')}</select></label><label class="search">${t('search')}<input id="search" type="search" value="${escape(query)}" placeholder="${t('search')}"></label></section><nav class="filter-tabs" aria-label="${t('resources')}">${['all','saved','review'].map(x=>btn(t(x==='all'?'allLessons':x),'filter',filter===x?'active':'',`data-filter="${x}" aria-pressed="${filter===x}"`)).join('')}</nav><div id="results">${libraryCards()}</div></main>`+footer();}
function footer(){return `<footer><strong>Oxford International School · Learn</strong><span>${t('progress')}</span><a href="${help()}" target="_blank" rel="noopener">${t('help')} ↗</a></footer>`;}
function noteContent(){return `<div class="reading-tip"><span>↗</span><div><b>${t('studyTip')}</b><p>${t('routine')}</p><p>${t('soloTip')}</p></div></div>${current.sections.map((section,i)=>`<section class="note-section"><div class="section-number">${String(i+1).padStart(2,'0')}</div><div><h2>${html(section.title)}</h2>${section.blocks.map(block=>`<article class="note-block">${prose(block.title,'h3')}${block.svg?`<figure class="diagram">${block.svg}<figcaption>${t(lang==='en'?'diagram':'diagramLanguage')}</figcaption></figure>`:block.image?`<figure class="diagram"><img src="../assets/${escape(block.image)}" alt="${escape(tr(block.title))}" loading="lazy"><figcaption>${t(lang==='en'?'diagram':'diagramLanguage')}</figcaption></figure>`:''}${block.lines.map(line=>prose(line)).join('')}${block.footnote?`<p class="source-note">${html(block.footnote)}</p>`:''}</article>`).join('')}</div></section>`).join('')}${current.related.length?`<section class="related"><h2>${t('related')}</h2>${current.related.map(id=>{const l=lessons.find(x=>x.id===id);return `<a href="?lesson=${encodeURIComponent(id)}&lang=${lang}" data-lesson="${escape(id)}">${html(l.title)} ↗</a>`;}).join('')}</section>`:''}`;}
function cardContent(){const cards=current.cards;if(!cards.length)return `<p>${t('noCards')}</p>`;cardIndex=Math.min(cardIndex,cards.length-1);const card=cards[cardIndex];return `<div class="recall-head"><p class="eyebrow">${t('card')} ${cardIndex+1} / ${cards.length}</p><p>${t('routine')}</p></div><article class="flashcard"><span class="card-spark">✧</span>${prose(card.front,'h2')}${cardOpen?`<div class="card-answer">${card.back.split('\n').map(x=>prose(x)).join('')}</div>`:''}${btn(t(cardOpen?'hide':'reveal'),'flip','primary')}</article><div class="card-controls">${btn('← '+t('previous'),'previous','secondary',cardIndex===0?'disabled':'')}${btn(t('repeat'),'card-review','secondary')}${btn(t('remembered'),'card-known','primary')}${btn(t('next')+' →','next','secondary',cardIndex===cards.length-1?'disabled':'')}</div>`;}
function practiceContent(){const answers=record().answers||{};return `<div class="practice-intro"><div><h2>${t('practice')}</h2><p>${t('readSource')}</p><small>${t('count')}: ${current.questions.filter(q=>answers[q.id]?.checked).length} / ${current.questions.length}</small></div>${btn(t('reset'),'reset','secondary')}</div>${current.questions.map((q,i)=>{const a=answers[q.id]||{},revealed=a.checked,correct=a.choice===q.answer;return `<article class="question" data-question="${escape(q.id)}"><p class="eyebrow">${t('question')} ${i+1} / ${current.questions.length}</p>${prose(q.prompt,'h3')}${q.lines.map(x=>prose(x)).join('')}${q.open||!q.options.length?`<label>${t('write')}<textarea class="response" data-response="${escape(q.id)}" rows="4">${escape(a.text||'')}</textarea></label>${btn(t('model'),'model','secondary',`data-id="${escape(q.id)}"`)}`:`<fieldset><legend class="sr-only">${html(q.prompt)}</legend>${q.options.map(o=>`<label class="answer-option ${a.choice===o.id?'chosen':''}"><input type="radio" name="q-${escape(q.id)}" value="${escape(o.id)}" data-choice="${escape(q.id)}" ${a.choice===o.id?'checked':''}><b>${escape(o.id)}</b><span>${html(o.label)}${bilingual&&lang!=='en'?`<small lang="en">${escape(o.label)}</small>`:''}</span></label>`).join('')}</fieldset>${btn(t('check'),'check','primary',`data-id="${escape(q.id)}"`)}`}${revealed?`<div class="answer-feedback ${q.open?'model':correct?'correct':'incorrect'}" role="status"><strong>${t(q.open?'selfCheck':correct?'correct':'incorrect')}</strong>${prose(q.model)}${!q.open?btn(t('tryAgain'),'retry-question','text-button',`data-id="${escape(q.id)}"`):''}</div>`:''}</article>`;}).join('')||`<p>${t('noQuiz')}</p>`}`;}
function notebookContent(){return `<section class="notebook"><span class="eyebrow">${t('reflection')}</span><h2>${t('notebook')}</h2><p>${t('prompt')}</p><textarea id="notebook" rows="14" placeholder="${t('notePlaceholder')}" aria-label="${t('notebook')}">${escape(record().note||'')}</textarea><div class="notebook-footer"><span id="note-status">${storageOK?t('savedNote'):t('storageError')}</span>${btn(t('download'),'download','secondary')}</div></section>`;}
function renderLesson(){const r=record();document.title=tr(current.title)+' · Learn';root.innerHTML=header()+`<main class="study"><a href="./?lang=${lang}" data-home class="back">← ${t('back')}</a><header class="lesson-heading"><div><p class="eyebrow">${t(current.subject)} · ${unitLabel(current.unit)} · ${escape(current.quarter)}</p><h1>${html(current.title)}</h1><p>${current.assessment?t('revision'):t('minutes')}</p></div><div class="lesson-actions">${btn(t(r.bookmarked?'bookmarked':'bookmark'), 'bookmark','secondary',`aria-pressed="${!!r.bookmarked}"`)}${btn(t('print'),'print','secondary')}</div></header>${lang!=='en'?`<div class="translation-note"><span>${t('translation')}</span><label><input type="checkbox" id="bilingual" ${bilingual?'checked':''}>${t('original')}</label></div>`:''}<nav class="study-tabs" aria-label="${t('resources')}">${['notes','cards','practice','notebook'].map(x=>btn(t(x), 'tab',tab===x?'active':'',`data-tab="${x}" aria-pressed="${tab===x}"`)).join('')}</nav><div class="study-layout"><div id="study-content">${tab==='notes'?noteContent():tab==='cards'?cardContent():tab==='practice'?practiceContent():notebookContent()}</div><aside class="study-sidebar"><div class="sidebar-card"><span class="eyebrow">${t('confidence')}</span>${btn(t('again'),'confidence','secondary '+(r.confidence==='again'?'selected':''),'data-value="again"')}${btn(t('understand'),'confidence','secondary '+(r.confidence==='understand'?'selected':''),'data-value="understand"')}<label class="review-check"><input id="reviewed" type="checkbox" ${r.reviewed?'checked':''}>${t('reviewed')}</label><small>${t('progress')}</small></div><div class="sidebar-help"><span class="help-icon">?</span><h3>${t('help')}</h3><a class="primary" href="${help()}" target="_blank" rel="noopener">WhatsApp ↗</a></div></aside></div></main>`+footer();}
function render(){document.documentElement.lang=lang==='zh'?'zh-Hans':lang;current?renderLesson():home();if(!storageOK)notice.textContent=t('storageError');}
async function setLanguage(code){const seq=++generation;lang=code;saved.lang=lang;persist();try{const dictionary=lang==='en'?{}:await fetch(`./locales/${lang}.json`).then(r=>{if(!r.ok)throw Error();return r.json();});if(seq!==generation)return;translations=dictionary;const next=new URL(location.href);next.searchParams.set('lang',lang);history.replaceState({},'',next);render();}catch{if(seq!==generation)return;translations={};render();notice.textContent=t('loadError');}}
function openLesson(id,push=true){const found=lessons.find(x=>x.id===id);if(!found)return;current=found;tab='notes';cardIndex=0;cardOpen=false;if(!found.classes.includes(saved.classId))saved.classId=found.classes[0];saved.lastLesson=id;persist();if(push)history.pushState({},'',`?lesson=${encodeURIComponent(id)}&lang=${lang}`);render();window.scrollTo(0,0);}
root.addEventListener('click',e=>{
 const link=e.target.closest('[data-lesson]');if(link){e.preventDefault();openLesson(link.dataset.lesson);return;}
 if(e.target.closest('[data-home]')){e.preventDefault();current=null;history.pushState({},'',`?lang=${lang}`);render();window.scrollTo(0,0);return;}
 const b=e.target.closest('[data-action]');if(!b)return;const action=b.dataset.action;
 if(action==='clear'){query='';filter='all';subject='all';quarter='all';home();return;}
 if(action==='filter'){filter=b.dataset.filter;home();return;}
 if(!current)return;
 const r=record();r.answers??={};
 if(action==='tab'){tab=b.dataset.tab;renderLesson();return;}
 if(action==='bookmark'){r.bookmarked=!r.bookmarked;persist();renderLesson();}
 if(action==='confidence'){r.confidence=b.dataset.value;persist();renderLesson();}
 if(action==='flip'){cardOpen=!cardOpen;renderLesson();}
 if(['next','previous','card-known','card-review'].includes(action)){if(action==='card-review'){r.confidence='again';persist();}if(action==='card-known'){r.cards??={};r.cards[cardIndex]=true;persist();}cardIndex=Math.max(0,Math.min(current.cards.length-1,cardIndex+(action==='previous'?-1:1)));cardOpen=false;renderLesson();}
 if(action==='check'||action==='model'){const a=r.answers[b.dataset.id]??={};if(action==='check'&&!a.choice){notify(t('choose'));return;}a.checked=true;persist();renderLesson();root.querySelector(`[data-question="${CSS.escape(b.dataset.id)}"]`)?.scrollIntoView({block:'nearest'});}
 if(action==='retry-question'){r.answers[b.dataset.id]={};persist();renderLesson();}
 if(action==='reset'){r.answers={};persist();renderLesson();}
 if(action==='print'){tab='notes';renderLesson();window.print();}
 if(action==='download'){const blob=new Blob([tr(current.title)+'\n\n'+(r.note||'')],{type:'text/plain;charset=utf-8'}),href=URL.createObjectURL(blob),a=document.createElement('a');a.href=href;a.download=current.id+'-notes.txt';a.click();setTimeout(()=>URL.revokeObjectURL(href),1000);}
});
root.addEventListener('change',e=>{const el=e.target;if(el.id==='language'){setLanguage(el.value);return;}if(el.id==='class'){saved.classId=el.value;subject='all';persist();home();}if(el.id==='subject'){subject=el.value;home();}if(el.id==='quarter'){quarter=el.value;home();}if(el.id==='bilingual'){bilingual=el.checked;renderLesson();}if(el.id==='reviewed'){record().reviewed=el.checked;persist();}if(el.dataset.choice){const r=record();r.answers??={};r.answers[el.dataset.choice]={choice:el.value,checked:false};persist();const question=el.closest('.question');question.querySelectorAll('.answer-option').forEach(label=>label.classList.toggle('chosen',label.contains(el)));question.querySelector('.answer-feedback')?.remove();}});
root.addEventListener('input',e=>{const el=e.target;if(el.id==='search'){query=el.value;document.querySelector('#results').innerHTML=libraryCards();}if(el.id==='notebook'){record().note=el.value;const ok=persist();document.querySelector('#note-status').textContent=t(ok?'savedNote':'storageError');}if(el.dataset.response){const r=record();r.answers??={};r.answers[el.dataset.response]={...r.answers[el.dataset.response],text:el.value};persist();}});
window.addEventListener('popstate',()=>{const id=new URL(location.href).searchParams.get('lesson');if(id)openLesson(id,false);else{current=null;render();}});
try{const r=await fetch('./lessons.json');if(!r.ok)throw Error();lessons=await r.json();if(!['7a','7b','8'].includes(saved.classId))saved.classId='7a';current=lessons.find(x=>x.id===url.searchParams.get('lesson'))||null;if(current&&!current.classes.includes(saved.classId))saved.classId=current.classes[0];await setLanguage(lang);}catch{root.innerHTML=`<main class="empty"><h1>${t('loadError')}</h1><a href="">${t('retry')}</a></main>`;}
