// Input: Natural Earth public-domain ne_110m_admin_0_countries.geojson.
// Download instructions and provenance are in docs/map-sources.md.
import fs from 'node:fs';
const data=JSON.parse(fs.readFileSync('output/ne-countries.geojson','utf8'));
const project=(lon,lat,regional)=>regional?[(lon+25)*12,(74-lat)*20]:[(lon+180)*2.5,(90-lat)*2.5];
const path=(geometry,regional)=>{
 const polys=geometry.type==='Polygon'?[geometry.coordinates]:geometry.coordinates;
 return polys.map(p=>p.map(r=>r.map(([lon,lat],i)=>(i?'L':'M')+project(lon,lat,regional).map(n=>n.toFixed(1)).join(' ')).join('')+'Z').join('')).join('');
};
const shapes=data.features.map(f=>({name:f.properties.ADMIN,world:path(f.geometry,false),europe:path(f.geometry,true)}));
fs.writeFileSync('src/atlas-paths.js','// Natural Earth 1:110m Admin 0 countries, public domain; generated by scripts/build-atlas.mjs.\nexport const atlasPaths='+JSON.stringify(shapes)+';\n');
console.log(`Bundled ${shapes.length} country outlines`);
